### ISSUE TITLE
About the screen capture and gif maker software?

### ISSUE THREAD

**Issue by whaomian** [rnystrom/RNFrostedSidebar#10]
Great effect!

What are the software you use to capture the screen animation, and make the capture video into gif?

Thanks a lot.

**Comment by rnystrom** [comment]
Sure! I use [Screenflick](http://www.araelium.com/screenflick/) to capture the video at the exact resolution I need. Then export the video as a .mov.

Import the .mov into Photoshop and play with the frame timings. Get rid of everything you don't need to get a tight loop. Export as a .gif, tweaking settings to get file size down while still retaining image quality, and bam! Make sure to tick the loop forever option too.
