### ISSUE TITLE
Slow Performance on iOS7 on iPad 3

### ISSUE THREAD

**Issue by jackkwok** [rnystrom/RNFrostedSidebar#14]
I tried the example app on iOS 7 / iPad 3 and the performance was slow.  It took closed to 2 seconds for menu to pop out.

When I tried the sample app on iOS 7 / iPhone 4, performance was very fast.

Those are the only devices I have so I don't know the performance on, say, iPad 4.

**Comment by TheAppleWizz** [comment]
i think thats because it takes a screen shot to do the frost.

**Comment by rnystrom** [comment]
The screenshot operation is horrible on my iPad 3 as well, just something I kind of deal w/. 2 seconds sounds crazy though.

How many images/buttons are you loading?

**Comment by biocross** [comment]
I have just 5 buttons, but it still takes like 2 seconds to load the menu on my iPad 3. Any fix?
