### ISSUE TITLE
How can i use the RNFrostedSidbar on iOS6 ?

### ISSUE THREAD

**Issue by Vanson** [rnystrom/RNFrostedSidebar#15]
How can i use the RNFrostedSidbar on iOS6 ?

**Comment by rnystrom** [comment]
Are you using Xcode 5? If you're using Xcode 4 you should be fine. 

If you're building with Xcode 5 but targeting iOS 6 take a look [at this issue thread](https://github.com/rnystrom/RNFrostedSidebar/issues/11).
