### ISSUE TITLE
Add text labels under each Item in the Sidebar.

### ISSUE THREAD

**Issue by biocross** [rnystrom/RNFrostedSidebar#16]
I want to use the sidebar as the navigation menu in my application. I am trying to make the icons as descriptive as possible, but it's always better to have Text Labels for each of them.

**Comment by rnystrom** [comment]
Pinging @appdicted because he pulled off added labels. I'm not really interested in adding this feature b/c the control was never intended to be used w/ it. I'd welcome a pull request though.

**Comment by appdicted** [comment]
I am tweaking the code that I wrote for labels, but will gladly share as soon as it is done. I am also having some fun as possibly using this to display photos. My apps are mostly all photo layer apps, such as Tattoo You. Currently I use a coverflow that is not as fun as this control.

**Comment by biocross** [comment]
Please do let me know when you push labels. I really need it for an app of mine. This sidebar is as it is amazing, but it becomes a little hard to use as navigation if your icons / options are not obvious enough. Thanks.

**Comment by pavankataria** [comment]
@appdicted Any update on the added labels?
