### ISSUE TITLE
Item label

### ISSUE THREAD

**Issue by dmi3j** [rnystrom/RNFrostedSidebar#18]
Could you, please, add item label? Would be nice to have text under the "circle".

**Comment by rnystrom** [comment]
Pinging @appdicted because he pulled off added labels. I'm not really interested in adding this feature b/c the control was never intended to be used w/ it. I'd welcome a pull request though.

**Comment by biocross** [comment]
Any progress @appdicted?

**Comment by appdicted** [comment]
Yes, code is just currently really ugly. I need to add some easy to read and adapt options. Also adding the ability to choose square border or round. I am using both right now, which I created a second, well and third delegate to try it out. Also I adjusted some padding around the buttons and even made one that goes horizontal layout... Not saying all this to tease, just to update on how this is morphing on my end.

Rory Boyer
roryboyer@gmail.com
Appdicted.com

**Comment by biocross** [comment]
I understand. Do you mind pushing what is done till now, so that we can also tinker with it?

**Comment by appdicted** [comment]
I'd push right now, but I am brand new to github and it's not integrated at all with my practice projects.

I will look at this tonight or send me an email directly and I'll pass you what I have.

Rory Boyer
801-244-3223
roryboyer@gmail.com
Appdicted.com

**Comment by pavankataria** [comment]
Hey @appdicted , hopefully you've become accustomed to github pushing, any chance you could push what you have till now, so that we can play from what you have so far? I will send you an email if you'd rather pass on what you have through there. Thank you appdicted.

**Comment by appdicted** [comment]
Looks like someone beat me to updating to add labels, so I won't be adding my solution as it's already done. Unfortunately, I was away from coding the past couple months as I own another business that gets really busy through the holidays. I have submitted my app "Mens Hairstyles" with this menu implemented if anyone wants to see it in a live app. It is in version 2.5 and should be approved this week. I have menus on both sides of the screen for different functions.
