### ISSUE TITLE
To remove circular effect

### ISSUE THREAD

**Issue by PreetySingh** [rnystrom/RNFrostedSidebar#29]
How can I remove the white circle that is been added to each of the item. I changed the tint colour but still there is gap between two item because the circle is still being created.

thank you.

**Comment by PreetySingh** [comment]
Because of the circle present:
![reason](https://f.cloud.github.com/assets/5540027/2385835/2a446692-a923-11e3-9464-0cffb5a63866.png)

It looks like this:
![effect](https://f.cloud.github.com/assets/5540027/2385837/2fafc9aa-a923-11e3-95ca-5442952fdf92.png)

I would like to remove white circle. I am a newbie help will be appreciated. Thanks, Kindly help me.

**Comment by leoopaiva** [comment]
is just define the background of them as clear color

callout.backgroundcolor = [UIColor ClearColor];

**Comment by PreetySingh** [comment]
Thanks.. :)
