### ISSUE TITLE
Change size of View.

### ISSUE THREAD

**Issue by martingodec** [rnystrom/RNFrostedSidebar#3]
Good morning. I would like to know how I can change the size of the view, as I have this problem.  I am using Xcode 5, and running IOS 7.
![img_3224](https://f.cloud.github.com/assets/4060027/1089569/742d07b6-1646-11e3-8e86-871f47721f6d.PNG)

Thank you.

**Comment by zzz6519003** [comment]
i don't get it.... please explain more~~~

**Comment by martingodec** [comment]
The problem I have is this. I put the driver and everything works perfectly, the problem I have is that I can not make the icons disappear at the height of NavogationBar.
I do not speak good English, sorry for not being able to express myself well.

**Comment by rnystrom** [comment]
Which view are you presenting the control in?

**Comment by rnystrom** [comment]
Another possible solution, try using [<code>-showInViewController:</code>](https://github.com/rnystrom/RNFrostedSidebar/blob/master/RNFrostedSidebar.h#L75) and displaying the control in your VC and _not_ in the nav controller.

I'll be removing this in a week if its dead.
