### ISSUE TITLE
Handle rotation of orientation on iOS 7+

### ISSUE THREAD

**Issue by skull-squadron** [rnystrom/RNFrostedSidebar#37]
### Use-case A

![rotation](http://content.screencast.com/users/zxcvxzcvxcv/folders/Jing/media/d05c7658-f7d2-4f05-9e63-8c8f1b7b9c31/00000059.png)
1. Start from **portrait**.
2. Present the sidebar.
3. Rotate to **landscape**.
4. Hmm, something doesn't look quite right.

---
### Use-case B

![rotation](http://content.screencast.com/users/zxcvxzcvxcv/folders/Jing/media/0410ac48-d7ad-43c3-af53-5e819cb8fd68/00000060.png)
1. Start from **landscape**.
2. Present the sidebar.
3. Rotate to **portrait**.
4. Hmm, something doesn't look quite right either.

**Comment by skull-squadron** [comment]
**Potential fix:** https://github.com/zwaldowski/RNFrostedSidebar/commit/efca1d959b899ba31d242c6c96e80682d9ea0cf5

**Update:** Nope

**Comment by skull-squadron** [comment]
blurView's frame is being resized, but the the blured image isn't being updated.

![debug](http://content.screencast.com/users/zxcvxzcvxcv/folders/Jing/media/0049c5e8-24d1-45f0-9682-bc7135315d40/00000061.png)

(I might find & patch the root cause another day.)

**Comment by skull-squadron** [comment]
Maybe related to #26

**Comment by skull-squadron** [comment]
A temporary hack might be to hide the sidebar before a rotation and show it after.

**Comment by skull-squadron** [comment]
Fixed it with an epic saga of refactoring goodness.  The bar dissolves out and then dissolves back in.  Looks it was a screen-door effect combined with not calling the layout code on orientation change.

**Comment by skull-squadron** [comment]
There is a bug in the above commit, but it's been resolved in my fork.

**Comment by MP85** [comment]
I was to report the same bug
