### ISSUE TITLE
In ios 7 if i try to push a ViewController from your code it doesn't pass the Navigationbar but in iOS 6 it does.

### ISSUE THREAD

**Issue by TheAppleWizz** [rnystrom/RNFrostedSidebar#8]
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
  NSLog(@"Tapped item at index %i",index);
  
  if (index == 1) {
      MYViewController *controller = [[MYViewController alloc] init];
      [self.navigationController pushViewController:controller animated:YES];
        [sidebar dismiss];
  
  }

}

do you have any idea what can be happening.

**Comment by davidSantmo** [comment]
I have the same problem but instead of ios7 in ios6

**Comment by TheAppleWizz** [comment]
What version of ios 6 are you using I'm testing it in ios 6.0 and in ios 7  it woks if I make it with xcode 4 ios 6.1 with development target ios 6.0

**Comment by davidSantmo** [comment]
hi' thanks, my problem is with the target version (ios6.1) in iO7

**Comment by rnystrom** [comment]
So for instance, you have a nav VC w/ root VC MYRootController. From MYRootController you present the sidebar. After selecting a button, MYRootController creates another VC and pushes it onto the nav stack.

You're building targetting min iOS 6.1. When running on iOS 7 the nav VC doesn't display the nav bar on the new VC, but on iOS 6 it does?

Have you tried messing with <code>navigationBarHidden</code> from the new VC?

**Comment by TheAppleWizz** [comment]
Yes that's exactly what I'm doing No, I haven't I will try it as soon as I can thanks

**Comment by TheAppleWizz** [comment]
i tried it, it didn't work.

**Comment by nessalauren5** [comment]
I have ~~a variation of~~ the same problem. In IOS7 when returning from a pushed view, the original view no longer has a navigationBar. 

~~As a solution to your problem~~ this is how I push my navigation controller (the bar does not show up on the pushed screen, but if i tap where the back button should be, it returns me to the original view.)

```
[sidebar dismiss]
[self performSegueWithIdentifier:@"toAnotherView" sender:self]; //this is a push segue
```

Can anyone help me with my issue? Returning to the original view somehow gets rid of the navigation controller. I tried changing top bar from inferred to navigation bar, didn't work. I also tried changing navigationBarHidden.

**Comment by rnystrom** [comment]
Another possible solution, try using [<code>-showInViewController:</code>](https://github.com/rnystrom/RNFrostedSidebar/blob/master/RNFrostedSidebar.h#L75) and displaying the control in your VC and _not_ in the nav controller.

**Comment by nessalauren5** [comment]
When i use -showInViewController: it displays the control underneath the navbar. This I could deal with, but now clicking on the control no longer calls didTapItemAtIndex: and I cannot segue away from the viewcontroller.

**Comment by mrodalgaard** [comment]
I solved the visual problem @nessalauren5 is seeing by hiding/showing the navigation bar in RNFrostedSidebar callbacks like this:

```
- (void)sidebar:(RNFrostedSidebar *)sidebar willDismissFromScreenAnimated:(BOOL)animatedYesOrNo {
    [self.navigationController setNavigationBarHidden:NO animated:animatedYesOrNo];
}

- (void)sidebar:(RNFrostedSidebar *)sidebar willShowOnScreenAnimated:(BOOL)animatedYesOrNo {
    [self.navigationController setNavigationBarHidden:YES animated:animatedYesOrNo];
}
```

Combined with @rnystrom suggestion of using -showInViewController.

This temporary hides the navigation bar when the sidebar is shown with smooth animation. Using segue from -didTapItemAtIndex works perfectly with this setup. iOS7.

**Comment by nessalauren5** [comment]
Okay. so this must be a side effect of my implementation. I tried your fix, and am still seeing the issue. Can you post your code here? My viewcontroller is embedded in UINavController..when I call showInViewController:self my didTapItemAtIndex does not respond. When I call with self.navigationController it responds but I see the issue.

When i push to the screen i see the navigation bar. when i return its gone. am i supposed to show the Frosted controller when i return from the pushed view? Thanks for your help! @MRodalgaard

**Comment by mrodalgaard** [comment]
I made a gist with my implementation, but there's no real magic happening; https://gist.github.com/MRodalgaard/7079502

**Comment by nessalauren5** [comment]
@MRodalgaard my code is the exact same except my viewcontroller is

```
ViewController<GMSMapViewDelegate,CLLocationManagerDelegate, RNFrostedSidebarDelegate,UITableViewDataSource,UITableViewDelegate>
```

And yours is embedded in a nav controller too? Weird.

**Comment by nessalauren5** [comment]
@MRodalgaard fixed it. moved my delegate declarations from the interface inside the .m to the .h

fix works for me now.

**Comment by rnystrom** [comment]
@MRodalgaard if you think this is an issue I need to address let me know. Or if you've found a solution I would gladly accept a PR. Thanks for you work!

**Comment by mrodalgaard** [comment]
It's more of a feature request. I'll think about it and if I find a good solution I'll make a feature request with a solution. Thank you.

**Comment by kvting** [comment]
Another solution would be to add a completion block to `dismissAnimated:(BOOL)animated` so that it doesn't temporarily hides the navigation bar when the sidebar is shown (in @MRodalgaard solution) and doesn't need to use `showInViewController:` (in @nessalauren5 suggestion).
The only thing that you have to make sure is to push your next viewController when the sidebar has been dismissed completely.
I'll send a pull request to implement if you are interested.

**Comment by lewis89** [comment]
Wondering if somebody can help me I'm really new to iOS programming only been doing it a week or so picking it up as i go along. I've managed to get the sidebar up on my first view controller but i don't know how to go about getting each icon when clicked to connect and open another view controller. I'm thinking its to do with this:

(void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
NSLog(@"Tapped item at index %i",index);

if (index == 1) {
MYViewController *controller = [[MYViewController alloc] init];
[self.navigationController pushViewController:controller animated:YES];
[sidebar dismiss];

}

}

But still can't make anything happen being trying for hours any help would be appreciated thanks.

**Comment by nessalauren5** [comment]
try index.row == 1

On Tue, Nov 12, 2013 at 9:30 PM, lewylad notifications@github.com wrote:

> Wondering if somebody can help me I'm really new to iOS programming only
> been doing it a week or so picking it up as i go along. I've managed to get
> the sidebar up on my first view controller but i don't know how to go about
> getting each icon when clicked to connect and open another view controller.
> I'm thinking its to do with this:
> 
> (void)sidebar:(RNFrostedSidebar *)sidebar
> didTapItemAtIndex:(NSUInteger)index {
> NSLog(@"Tapped item at index %i",index);
> 
> if (index == 1) {
> MYViewController *controller = [[MYViewController alloc] init];
> [self.navigationController pushViewController:controller animated:YES];
> [sidebar dismiss];
> 
> }
> 
> }
> 
> But still can't make anything happen being trying for hours any help would
> be appreciated thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rnystrom/RNFrostedSidebar/issues/8#issuecomment-28357418
> .

## 

Robert Orben  - "To err is human - and to blame it on a computer is even
more so."

**Comment by nessalauren5** [comment]
also the first index will most likely be 0, fyi, so for your first
controller try index.row==0

On Tue, Nov 12, 2013 at 9:36 PM, Vanessa Anderson
nessa.lauren5@gmail.comwrote:

> try index.row == 1
> 
> On Tue, Nov 12, 2013 at 9:30 PM, lewylad notifications@github.com wrote:
> 
> > Wondering if somebody can help me I'm really new to iOS programming only
> > been doing it a week or so picking it up as i go along. I've managed to get
> > the sidebar up on my first view controller but i don't know how to go about
> > getting each icon when clicked to connect and open another view controller.
> > I'm thinking its to do with this:
> > 
> > (void)sidebar:(RNFrostedSidebar *)sidebar
> > didTapItemAtIndex:(NSUInteger)index {
> > NSLog(@"Tapped item at index %i",index);
> > 
> > if (index == 1) {
> > MYViewController *controller = [[MYViewController alloc] init];
> > [self.navigationController pushViewController:controller animated:YES];
> > [sidebar dismiss];
> > 
> > }
> > 
> > }
> > 
> > But still can't make anything happen being trying for hours any help
> > would be appreciated thanks.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/rnystrom/RNFrostedSidebar/issues/8#issuecomment-28357418
> > .
> 
> ## 
> 
> Robert Orben  - "To err is human - and to blame it on a computer is even
> more so."

## 

Robert Orben  - "To err is human - and to blame it on a computer is even
more so."

**Comment by lewis89** [comment]
yeah i know the indexes but I'm not sure what code i need its not working so I'm back to this:

(void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
NSLog(@"Tapped item at index %i",index);

if (index == 1) {

}

}

i need the code to present the view controller I've tried all sorts including segues just can't seem to get the right code

**Comment by nessalauren5** [comment]
have you set the delegate? here is my code:
    RNFrostedSidebar *callout = [[RNFrostedSidebar alloc] initWithImages:images
selectedIndices:nil borderColors:colors];

 callout.delegate = self;

```
[callout showInViewController:self animated:YES];
```

#pragma mark - RNFrostedSidebarDelegate
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index
  {    NSLog(@"Tapped item at index %i",index);
  
  [sidebar dismiss];
  
  switch(index){
  
  ```
  case 0:{//do stuff here
  ```

break;

```
    }
```

}

}

On Tue, Nov 12, 2013 at 9:40 PM, lewylad notifications@github.com wrote:

> yeah i know the indexes but I'm not sure what code i need its not working
> so I'm back to this:
> 
> (void)sidebar:(RNFrostedSidebar *)sidebar
> didTapItemAtIndex:(NSUInteger)index {
> NSLog(@"Tapped item at index %i",index);
> 
> if (index == 1) {
> 
> }
> 
> }
> 
> i need the code to present the view controller I've tried all sorts
> including segues just can't seem to get the right code
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rnystrom/RNFrostedSidebar/issues/8#issuecomment-28357939
> .

## 

Robert Orben  - "To err is human - and to blame it on a computer is even
more so."

**Comment by lewis89** [comment]
thanks ill compare mine to yours see whats going wrong this is mine:

RNFrostedSidebar *callout = [[RNFrostedSidebar alloc] initWithImages:images selectedIndices:self.optionIndices borderColors:colors];
    //    RNFrostedSidebar *callout = [[RNFrostedSidebar alloc] initWithImages:images];
    callout.delegate = self;
    //    callout.showFromRight = YES;
    [callout show];
}

#pragma mark - RNFrostedSidebarDelegate
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
  NSLog(@"Tapped item at index %i",index);
  
  if (index == 1) {
  
  }
  
  if (index == 2) {
  
  }

}

**Comment by lewis89** [comment]
Tried this now but no luck i click and all that happens is the sidebar dismiss no view controller :(

 RNFrostedSidebar *callout = [[RNFrostedSidebar alloc] initWithImages:images selectedIndices:nil borderColors:colors];

```
callout.delegate = self;

[callout showInViewController:self animated:YES];
```

}

#pragma mark - RNFrostedSidebarDelegate
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
  NSLog(@"Tapped item at index %i",index);
  
  [sidebar dismiss];
  
  UIViewController *anotherVC = nil;
  
  switch(index){
  
  ```
  case 0:{
  
      anotherVC = [[calView2 alloc] init];
      break;
  
  }
  ```
  
  }
  
   [anotherVC setModalPresentationStyle:UIModalPresentationFormSheet];
   [anotherVC setModalTransitionStyle:UIModalTransitionStyleFlipHorizontal];
  [self.navigationController presentViewController:anotherVC animated:YES completion:NULL];

}

**Comment by nessalauren5** [comment]
If you are initializing a view controller of type calView2 the line would
look like this

calView2 *anotherVC = [[calView2 alloc]init];

and secondly, are you absolutely sure that the current view has a
navigation controller? try this line and see what happens:

[self presentViewController:anotherVC animated:YES completion:nil];

On Tue, Nov 12, 2013 at 10:09 PM, lewylad notifications@github.com wrote:

> Tried this now but no luck i click and all that happens is the sidebar
> dismiss no view controller :(
> 
> RNFrostedSidebar *callout = [[RNFrostedSidebar alloc]
> initWithImages:images selectedIndices:nil borderColors:colors];
> 
> callout.delegate = self;
> 
> [callout showInViewController:self animated:YES];
> 
> }
> 
> #pragma mark - RNFrostedSidebarDelegate
> 
>    -
> 
>    (void)sidebar:(RNFrostedSidebar *)sidebar
>    didTapItemAtIndex:(NSUInteger)index {
>    NSLog(@"Tapped item at index %i",index);
> 
>    [sidebar dismiss];
> 
>    UIViewController *anotherVC = nil;
> 
>    switch(index){
> 
>    case 0:{
> 
> ```
>    anotherVC = [[calView2 alloc] init];
>    break;
> ```
> 
>    }
> 
>    }
> 
>    [anotherVC setModalPresentationStyle:UIModalPresentationFormSheet];
>    [anotherVC
>    setModalTransitionStyle:UIModalTransitionStyleFlipHorizontal];
>    [self.navigationController presentViewController:anotherVC
>    animated:YES completion:NULL];
> 
> }
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rnystrom/RNFrostedSidebar/issues/8#issuecomment-28359522
> .

## 

Robert Orben  - "To err is human - and to blame it on a computer is even
more so."

**Comment by lewis89** [comment]
to be honest i really don't know what I'm doing all i need is to be able to navigate between views by clicking on each of the buttons do you have code that enables you to go from your current view controller to another by clicking one of the buttons?

**Comment by lewis89** [comment]
after editing to what you suggest it takes me to a black screen when i click

**Comment by nessalauren5** [comment]
That means it is taking you to the new view. Now you need to make sure you add things to your view using [self.view addSubview:**]

Also, if you are trying to go to a view that you created in storyboard you should probably use a segue or 
Instantiate it using the storyboard id

**Comment by lewis89** [comment]
i don't know how to do any of that this is the first thing I've tried to do so I'm still new at all this I've tried a segue but wasn't sure how to do it must have got it wrong

**Comment by lewis89** [comment]
managed to get it to work :p  
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
  NSLog(@"Tapped item at index %i",index);
  
  [sidebar dismiss];
  
  switch(index){
  
  ```
  case 2:{
  
      UIViewController *anotherVC = nil;
      anotherVC = [[calView2 alloc] init];
  
      anotherVC = [self.storyboard instantiateViewControllerWithIdentifier:@"view2"];
  
       [anotherVC setModalPresentationStyle:UIModalPresentationFormSheet];
       [anotherVC setModalTransitionStyle:UIModalTransitionStyleFlipHorizontal];
       [self presentViewController:anotherVC animated:YES completion:nil];
      break;
  }
  ```
  
  }}

thanks for the help :-)
