### ISSUE TITLE
Changing views when using storyboards

### ISSUE THREAD

**Issue by Dragsbaek** [rnystrom/RNFrostedSidebar#9]
How would i use the function to change views created with storyboard?
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
  NSLog(@"Tapped item at index %i",index);
  if (index == 1) {
      //code to change view
      [sidebar dismiss];
  }
  }

**Comment by ashishfission** [comment]
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
  NSLog(@"Tapped item at index %i",index);
  if (index == 0) {
      [sidebar dismiss];
      [self performSegueWithIdentifier:@"View1" sender:self];
  
  }
  if (index == 1) {
      [sidebar dismiss];
      [self performSegueWithIdentifier:@"view2" sender:self];
  
  }
  if (index == 2) {
      [sidebar dismiss];
      [self performSegueWithIdentifier:@"view3" sender:self];
  
  }
  
  if (index == 3) {
      [sidebar dismiss];
      [self performSegueWithIdentifier:@"view4" sender:self];
  
  }
  if (index == 4) {
      [sidebar dismiss];
      [self performSegueWithIdentifier:@"view5" sender:self];
  
  }
  }
